"""Initial Schema

Revision ID: 4cfd68e5f08e
Revises: 
Create Date: 2026-02-12 12:02:40.003906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cfd68e5f08e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_id', sa.UUID(), nullable=False),
    sa.Column('to_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_links_from_id'), 'memory_links', ['from_id'], unique=False)
    op.create_index(op.f('ix_memory_links_relation_type'), 'memory_links', ['relation_type'], unique=False)
    op.create_index(op.f('ix_memory_links_to_id'), 'memory_links', ['to_id'], unique=False)
    op.create_table('memory_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('scope', sa.Enum('AGENT', 'TEAM', 'ORG', 'GLOBAL', name='memoryscope'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('memory_type', sa.Enum('FACT', 'PREFERENCE', 'EXPERIENCE', 'PLAN', 'BUG', 'INSIGHT', 'OTHER', name='memorytype'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_agent', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('conflict_flag', sa.Boolean(), nullable=False),
    sa.Column('embedding_id', sa.String(length=255), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_records_agent_id'), 'memory_records', ['agent_id'], unique=False)
    op.create_index(op.f('ix_memory_records_conflict_flag'), 'memory_records', ['conflict_flag'], unique=False)
    op.create_index(op.f('ix_memory_records_created_at'), 'memory_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_memory_records_embedding_id'), 'memory_records', ['embedding_id'], unique=False)
    op.create_index(op.f('ix_memory_records_expires_at'), 'memory_records', ['expires_at'], unique=False)
    op.create_index(op.f('ix_memory_records_is_deleted'), 'memory_records', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_memory_records_memory_type'), 'memory_records', ['memory_type'], unique=False)
    op.create_index(op.f('ix_memory_records_org_id'), 'memory_records', ['org_id'], unique=False)
    op.create_index(op.f('ix_memory_records_scope'), 'memory_records', ['scope'], unique=False)
    op.create_index(op.f('ix_memory_records_team_id'), 'memory_records', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_records_team_id'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_scope'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_org_id'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_memory_type'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_is_deleted'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_expires_at'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_embedding_id'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_created_at'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_conflict_flag'), table_name='memory_records')
    op.drop_index(op.f('ix_memory_records_agent_id'), table_name='memory_records')
    op.drop_table('memory_records')
    op.drop_index(op.f('ix_memory_links_to_id'), table_name='memory_links')
    op.drop_index(op.f('ix_memory_links_relation_type'), table_name='memory_links')
    op.drop_index(op.f('ix_memory_links_from_id'), table_name='memory_links')
    op.drop_table('memory_links')
    # ### end Alembic commands ###
